name: my_app
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  get_it: ^7.6.0
  injectable: ^2.1.2
  arcade:
    git:
      url: git@github.com:ishafiul/arcade.git
      ref: fix/process_signal_watchers_windows
      path: packages/arcade

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.5
  injectable_generator: ^2.1.6
